name: Terraform Workflow
 
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      USER_NAME: "${{ env.USER_NAME }}"
      TOKEN: "${{ secrets.TOKEN }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          
          terraform init
          # Other Terraform commands...
