name: Your Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_github_username: ${{ secrets.GITHUB_USERNAME }}
      TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize Terraform
        run: |
          
          terraform init \
            -backend-config="username=${TF_VAR_github_username}" \
            -backend-config="token=${TF_VAR_github_token}"
