name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          export GITHUB_TOKEN=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
           terraform init 


      - name: Terraform Plan
        run: terraform plan -input=false

      # Add more steps as needed for apply, destroy, etc.
