name: Terraform Workflow

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          echo "TF_VAR_gh_username=Rahulsurya1" >> $GITHUB_ENV
          echo "TF_VAR_gh_repo=checkaccesstoken"" >> $GITHUB_ENV
          echo "TF_VAR_gh_token=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" >> $GITHUB_ENV

          terraform init 
          terraform plan
